efpRegistryServer/src/main/java/cz/zcu/kiv/efps/registry/server/beans/EfpBean.java
package cz.zcu.kiv.efps.registry.server.beans;

import java.io.Serializable;

import cz.zcu.kiv.efps.registry.server.entities.EfpEntity;

/**
 * Assignment bean object for handling forms.
 * @author Bc. Tomas Kohout
 * @since 25.10.2011
 */
public class EfpBean implements Serializable {

  /** serial UID. */
  private static final long serialVersionUID = 3735143062901457358L;

  /** {@link EfpEntity} object. */
  private EfpEntity efpEntity;
  /** ID of parent GR. */
  private int grId;

  /**
   * Getter.
   * @return {@link EfpEntity}
   */
  public EfpEntity getEfpEntity() {
    return efpEntity;
  }

  /**
   * Setter.
   * @param efpEntity {@link EfpEntity}
   */
  public void setEfpEntity(final EfpEntity efpEntity) {
    this.efpEntity = efpEntity;
  }

  /**
   * Getter.
   * @return {@link Integer}
   */
  public int getGrId() {
    return grId;
  }

  /**
   * Setter.
   * @param grId {@link Integer}
   */
  public void setGrId(final int grId) {
    this.grId = grId;
  }
}

efpRegistryServer/src/main/java/cz/zcu/kiv/efps/registry/server/entities/EfpEntity.java
package cz.zcu.kiv.efps.registry.server.entities;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * @author Kamil Jezek [kjezek@kiv.zcu.cz]
 *
 */
@Entity
@Table(name = "efp",
     uniqueConstraints = {@UniqueConstraint(columnNames = { "name", "gr_id" }) }
)
public class EfpEntity  {

    /** ID. */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    /** A name of the EFP. */
    @Column(nullable = false)
    private String name;
    /** A measuring unit. */
    private String unit;
    /** A user defined gamma. */
    private String gamma;
    /** A value type of this EFP.  */
    private Class<?> valueType;

    /** A list of properties this EFP is derived from. */
    @ManyToMany
    @JoinTable(name = "derived_efp",
            uniqueConstraints = {@UniqueConstraint(columnNames
                    = {"derived_efp_id", "efp_id" }) },
            joinColumns = {@JoinColumn(name = "derived_efp_id") },
            inverseJoinColumns = {@JoinColumn(name = "efp_id") })
    private List<EfpEntity> derivedFromEfps;

    /** A link to GR. */
    @ManyToOne
    @JoinColumn(name = "gr_id", nullable = false)
    private GrEntity gr;

    /** Value names for LRs. */
    @ManyToMany
    @JoinTable(name = "efp_names",
            inverseJoinColumns = {@JoinColumn(name = "name_id", nullable = true) })
    private List<ValueNameEntity> valueNames;

    /**
     * @return the derivedFromEfps
     */
    public List<EfpEntity> getDerivedFromEfps() {
        return derivedFromEfps;
    }

    /**
     * @param derivedFromEfps the derivedFromEfps to set
     */
    public void setDerivedFromEfps(final List<EfpEntity> derivedFromEfps) {
        this.derivedFromEfps = derivedFromEfps;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /** Max length for name. */
    private static final int NAME_CONSTANT_MAX_LENGTH = 14;
    /** Start position for second part in name. */
    private static final int NAME_CONSTANT_SECOND_POSITION = 13;

    /**
     * Get optimized name with formatting.
     * @return String
     */
    public String getOptimizedName() {
      if (name.length() <= NAME_CONSTANT_MAX_LENGTH) {
        return name;
      } else {
        String firstPart = name.substring(0, NAME_CONSTANT_SECOND_POSITION);
        String secondPart = name.substring(NAME_CONSTANT_SECOND_POSITION);
        return firstPart + "<br />" + secondPart;
      }
    }

    /**
     * @return the unit
     */
    public String getUnit() {
        return unit;
    }

    /**
     * @return the gamma
     */
    public String getGamma() {
        return gamma;
    }

    /**
     * @return the valueNames
     */
    public List<ValueNameEntity> getValueNames() {
        return valueNames;
    }

    /**
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(final String unit) {
        this.unit = unit;
    }

    /**
     * @param gamma the gamma to set
     */
    public void setGamma(final String gamma) {
        this.gamma = gamma;
    }

    /**
     * @param valueNames the valueNames to set
     */
    public void setValueNames(final List<ValueNameEntity> valueNames) {
        this.valueNames = valueNames;
    }

    /**
     * @return the gr
     */
    public GrEntity getGr() {
        return gr;
    }

    /**
     * @param gr the gr to set
     */
    public void setGr(final GrEntity gr) {
        this.gr = gr;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(final Integer id) {
        this.id = id;
    }



    /**
     * @return the valueType
     */
    public Class<?> getValueType() {
        return valueType;
    }

    /**
     * @param valueType the valueType to set
     */
    public void setValueType(final Class<?> valueType) {
        this.valueType = valueType;
    }

    /** {@inheritDoc} */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((gr == null) ? 0 : gr.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        return result;
    }

    /** {@inheritDoc} */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        EfpEntity other = (EfpEntity) obj;
        if (gr == null) {
            if (other.gr != null) {
                return false;
            }
        } else if (!gr.equals(other.gr)) {
            return false;
        }
        if (name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!name.equals(other.name)) {
            return false;
        }
        return true;
    }

    /** Class name max length. */
    private static final int CLASS_NAME_CONSTANT_LENGTH = 12;

    /**
     * Get prepared simple name with formatting.
     * @return String
     */
    public String getPreparedValueType() {
      String result = getValueType().getSimpleName();
      if (result.length() > CLASS_NAME_CONSTANT_LENGTH) {
        result = result.substring(0, CLASS_NAME_CONSTANT_LENGTH) + ".";
      }
      return result;
    }
}

efpRegistryServer/src/main/java/cz/zcu/kiv/efps/registry/server/controllers/EfpController.java
package cz.zcu.kiv.efps.registry.server.controllers;

import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.hibernate3.HibernateTransactionManager;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.DefaultTransactionDefinition;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import cz.zcu.kiv.efps.registry.server.beans.EfpBean;
import cz.zcu.kiv.efps.registry.server.beans.ValueNameBean;
import cz.zcu.kiv.efps.registry.server.entities.EfpEntity;
import cz.zcu.kiv.efps.registry.server.entities.GrEntity;
import cz.zcu.kiv.efps.registry.server.entities.LrAssignmentEntity;
import cz.zcu.kiv.efps.registry.server.entities.LrEntity;
import cz.zcu.kiv.efps.registry.server.entities.UserEntity;
import cz.zcu.kiv.efps.registry.server.entities.UserRoleEntity;
import cz.zcu.kiv.efps.registry.server.entities.ValueNameEntity;
import cz.zcu.kiv.efps.registry.server.service.EfpService;
import cz.zcu.kiv.efps.registry.server.service.EntityTreeService;
import cz.zcu.kiv.efps.registry.server.service.GrService;
import cz.zcu.kiv.efps.registry.server.service.LrAssignmentService;
import cz.zcu.kiv.efps.registry.server.service.LrService;
import cz.zcu.kiv.efps.registry.server.service.UserService;
import cz.zcu.kiv.efps.registry.server.service.ValueNameService;
import cz.zcu.kiv.efps.registry.server.service.impl.ChoosenObject;
import cz.zcu.kiv.efps.registry.server.service.impl.EntityTree;
import cz.zcu.kiv.efps.registry.server.service.impl.EntityTypes;
import cz.zcu.kiv.efps.registry.server.tools.EfpUtils;

/**
 * Controller for handling with EFP (Assignments).
 */
@Controller("efpController")
public class EfpController {

  /** Logger. */
  private static final Logger LOGGER = LoggerFactory.getLogger(EfpController.class);

  /**
   * Method for showing EFP object in left object window.
   * @param grId String
   * @param lrId String
   * @param choosenObjectId String
   * @param packedListString String
   * @param ajaxEnabled String
   * @return {@link ModelAndView}
   * @throws EFPControllerException e
   */
  @RequestMapping(value = "/efpObject", params = {
      ControllerConst.MAIN_PARAM_GR_ID,
      ControllerConst.MAIN_CONTROLLER_PARAM_LR_ID,
      ControllerConst.MAIN_PARAM_CHOOSEN_OBJECT_ID,
      ControllerConst.MAIN_CONTROLLER_PARAM_PACKED_LIST,
      ControllerConst.LR_CONTROLLER_AJAX_ENABLED },
  method = RequestMethod.GET)
  public ModelAndView efpObject(
      @RequestParam(ControllerConst.MAIN_PARAM_GR_ID) final String grId,
      @RequestParam(ControllerConst.MAIN_CONTROLLER_PARAM_LR_ID) final String lrId,
      @RequestParam(ControllerConst.MAIN_PARAM_CHOOSEN_OBJECT_ID) final String choosenObjectId,
      @RequestParam(ControllerConst.MAIN_CONTROLLER_PARAM_PACKED_LIST)
      final String packedListString,
      @RequestParam(ControllerConst.LR_CONTROLLER_AJAX_ENABLED) final String ajaxEnabled)
  throws EFPControllerException {

    LOGGER.info("EfpController.efpObject(" + grId + "," + lrId + ","
        + choosenObjectId + ",[" + packedListString + "])");

    GrEntity grEntity = null;
    int grIdNum = 0;
    if (grId != null) {
      grIdNum = Integer.valueOf(grId);
    } else {
      grEntity = grService.findAll().get(0);
      if (grEntity != null) {
        grIdNum = grEntity.getId();
      }
    }

    // Construction of Model and View
    ModelAndView mav = new ModelAndView();
    if (ControllerConst.AJAX_ENABLED.equals(ajaxEnabled.toLowerCase())) {
      mav.setViewName("object_properties_ajax");
    } else {
      mav.setViewName("main");
    }

    List<Integer> packedList = EfpUtils.processPackedListString(packedListString);

    EntityTree entityTree = null;
    if (grIdNum != 0) {
      grEntity = grService.findById(grIdNum);
      if (packedList.isEmpty()) {
        entityTree = entityTreeService.createEntityTree(grIdNum);
      } else {
        entityTree = entityTreeService.createEntityTree(
            grIdNum,
            packedList);
      }
      mav.addObject(ControllerConst.MAIN_CONTROLLER_OBJECT_ENTITY_TREE, entityTree);
    }

    // gr entity list
    List<GrEntity> grEntities = new LinkedList<GrEntity>();
    grEntities = grService.findAll();
    if (grEntities != null && !grEntities.isEmpty()) {
      if (grEntity != null) {
        mav.addObject(
            ControllerConst.MAIN_CONTROLLER_OBJECT_CHOOSEN_GR, grEntity.getId());
      }
      mav.addObject(ControllerConst.MAIN_CONTROLLER_OBJECT_GR_ENTITIES, grEntities);
    }

    //prepare choosen object
    ChoosenObject choosenObject = entityTreeService.getChoosenObject(
        grId, EntityTypes.ASSIGNMENT.getName(),
        lrId + ControllerConst.ID_DELIMITER + choosenObjectId, entityTree, packedListString);
    if (choosenObject != null) {
      entityTree.selectObject(choosenObject.getType(), choosenObject);
      mav.addObject(ControllerConst.MAIN_PARAM_CHOOSEN_OBJECT, choosenObject);
    }

    // send packet list
    mav.addObject(ControllerConst.MAIN_CONTROLLER_PARAM_PACKED_LIST,
        packedListString);

    return mav;
  }

  /**
   * Delete EFP.
   * @param efpId String
   * @return String
   * @throws EFPControllerException e
   */
  @RequestMapping(value = "/deleteEfp", params = { ControllerConst.EFP_CONTROLLER_PARAM_EFP_ID })
  public String deleteEfp(@RequestParam(ControllerConst.EFP_CONTROLLER_PARAM_EFP_ID)
      final String efpId) throws EFPControllerException {

    LOGGER.info("Deleting EFP: " + efpId);

    TransactionStatus txStatus = transactionManager.getTransaction(
        new DefaultTransactionDefinition());

    // TODO delete assignments for EFP_ID

    try {
      efpService.deleteById(Integer.valueOf(efpId));
      transactionManager.commit(txStatus);
      LOGGER.info("*** DB COMMIT ***");
    } catch (Exception ex) {
      if (!txStatus.isCompleted()) {
        transactionManager.rollback(txStatus);
      }
      throw new EFPControllerException("Exception while deleting EFP (" + efpId + ").", ex);
    }

    // TODO  keep screen on LR
    return "redirect:/client/main/tree?"
    + ControllerConst.MAIN_PARAM_GR_ID
    + "="
    + "&" + ControllerConst.MAIN_PARAM_CHOOSEN_OBJECT_TYPE
    + "=" + "&" + ControllerConst.MAIN_PARAM_CHOOSEN_OBJECT_ID
    + "="
    + "&" + ControllerConst.MAIN_CONTROLLER_PARAM_PACKED_LIST
    + "=";
  }

  /**
   * Delete not assigned Efp.
   * @param efpId String
   * @return {@link ModelAndView}
   * @throws EFPControllerException e
   */
  @RequestMapping(
      value = "/deleteEfpAjax",
      params = { ControllerConst.EFP_CONTROLLER_PARAM_EFP_ID },
      method = RequestMethod.GET)
  public ModelAndView deleteEfpAjax(
      @RequestParam(ControllerConst.EFP_CONTROLLER_PARAM_EFP_ID) final String efpId)
  throws EFPControllerException {

    LOGGER.info("Deleting EFP: " + efpId);

    TransactionStatus txStatus = transactionManager.getTransaction(
        new DefaultTransactionDefinition());

    // deleting only not assigned EFP - it is OK

    try {
      efpService.deleteById(Integer.valueOf(efpId));
      transactionManager.commit(txStatus);
      LOGGER.info("*** DB COMMIT ***");
    } catch (Exception ex) {
      if (!txStatus.isCompleted()) {
        transactionManager.rollback(txStatus);
      }
      throw new EFPControllerException("Exception while deleting EFP (" + efpId + ").", ex);
    }

    ModelAndView mav = new ModelAndView("efp_1");
    mav.addObject(ControllerConst.EFP_CONTROLLER_NOT_ASSIGNED_EFP_LIST,
        efpService.getNotAssignedEfpList());
    return mav;
  }

  /**
   * Delete assignment.
   * @param assignmentId String
   * @return {@link ModelAndView}
   * @throws EFPControllerException e
   */
  @RequestMapping(
      value = "/deleteAssignmentAjax",
      params = { ControllerConst.EFP_CONTROLLER_ASSIGNMENT_ID },
      method = RequestMethod.GET)
  public ModelAndView deleteAssignmentAjax(
      @RequestParam(ControllerConst.EFP_CONTROLLER_ASSIGNMENT_ID) final String assignmentId)
  throws EFPControllerException {

    LrAssignmentEntity assignment = lrAssignmentService.findById(Integer.valueOf(assignmentId));

    if (assignment != null) {

      TransactionStatus txStatus = transactionManager.getTransaction(
          new DefaultTransactionDefinition());

      LOGGER.info("Deleting LRAssignment(ID=)" + assignmentId);

      try {
        lrAssignmentService.delete(assignment);
        transactionManager.commit(txStatus);
      } catch (AccessDeniedException de) {
        transactionManager.rollback(txStatus);
        return new ModelAndView("denied");
      } catch (Exception ex) {
        if (!txStatus.isCompleted()) {
          transactionManager.rollback(txStatus);
        }
        throw new EFPControllerException("Exception while deleting LR_ASSIGNMENT ("
            + assignmentId + ").", ex);
      }
    } else {
      LOGGER.warn("Assignment for deleting (" + assignmentId + ") was not found");
    }


efpRegistryServer/src/main/webapp/WEB-INF/jsp/assignment_list.jsp
<?xml version="1.0" encoding="UTF-8" ?>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<% request.setCharacterEncoding("utf-8"); %>
<% response.setCharacterEncoding("utf-8"); %>
          <c:forEach var="assignment" items="${assignments}">
            <tr>
              <td style="width: 200px; text-align: left;">${assignment.lr.name}</td>
              <td style="width: 200px; text-align: left;">${assignment.efp.name}</td>
              <td style="width: 200px; text-align: left;">${assignment.valueName.name}</td>
            </tr>
          </c:forEach>

efpRegistryServer/src/main/webapp/WEB-INF/jsp/delete_denied.jsp
denied delete

efpRegistryServer/src/main/webapp/WEB-INF/jsp/denied.jsp
<?xml version="1.0" encoding="UTF-8" ?>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<% request.setCharacterEncoding("utf-8"); %>
<% response.setCharacterEncoding("utf-8"); %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="description" content="EFP Repository" />
    <meta name="copyright" content="TomasKohout@2011" />
    <meta name="keywords" content="EFP, repository, storage, component, software, OSGi" />
    <meta http-equiv="Content-language" content="cs" />
    <meta name="author" content="Bc. Tomáš Kohout" />
    <title>EFP Repository</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/client/resources/css/styles_basic.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="${pageContext.request.contextPath}/client/resources/css/styles_print.css" type="text/css" media="print" />
    <script type="text/javascript" src="${pageContext.request.contextPath}/client/resources/js/jquery-1.7.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/client/resources/js/jquery.form.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/client/resources/js/tinyscrollbar.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/client/resources/js/scriptUtils.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/client/resources/js/jQuery_mousewheel_plugin.js"></script>
    <script type="text/javascript">
    </script>
  </head>
  <body>
    <div id="main">
      <div id="wizard" style="background-color: #FFFFFF;">
        <h1><spring:message code="efp.client.main.denied" /></h1>
      </div>
    </div>
  </body>
</html>

efpRegistryServer/src/main/webapp/WEB-INF/jsp/edit_value_result.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<% request.setCharacterEncoding("utf-8"); %>
<% response.setCharacterEncoding("utf-8"); %>
<p class="wizard" style="color: #00FF00; font-weight: bold;"><spring:message code="efp.client.val_3.edit_result" /></p>

efpRegistryServer/src/main/webapp/WEB-INF/jsp/efp_values_ajax_list.jsp
<?xml version="1.0" encoding="UTF-8" ?>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
      <table border="0" class="centered">
              <c:forEach var="value" items="${values}">
                <tr>
                  <td></td>
                  <td class="inside-boxed" style="text-align: left; padding-left: 5px; padding-right: 5px;">
                    <a href="${pageContext.request.contextPath}/client/value/valueScreen?gr_id=${choosen_gr}&value_id=${value.id}" title="<spring:message code='efp.client.assignment.edit' />" class="object-properties">${value.name}</a>
                  </td>
                  <td>
                    <a href="" title="<spring:message code='efp.client.assingment.delete' />" class="image" onclick="confirmDelete('<spring:message code="efp.client.efpScreen.assignment.confirm_delete" />', '${pageContext.request.contextPath}/client/efp/deleteValueEfpScreen?efp_id=${choosen_efp}&value_id=${value.id}');"><img src="${pageContext.request.contextPath}/client/resources/graphics/delete.png" width="16" height="16" alt="delete" title="" /></a>
                  </td>
                </tr>
              </c:forEach>
            </table>

efpRegistryServer/src/main/webapp/WEB-INF/jsp/login_exist.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<% request.setCharacterEncoding("utf-8"); %>
<% response.setCharacterEncoding("utf-8"); %>
  <spring:message code="efp.client.reg0.loginExist" />


efpRegistryServer/src/main/webapp/WEB-INF/jsp/lr2.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
              <div class="lr_name" style="background-image: url(${pageContext.request.contextPath}/client/resources/graphics/${choosenObject.backgroundImage}); background-repeat: no-repeat; background-position: 50% 50%; background-color: #FFFFFF; margin: 5px;">
                <h5 class="object-properties">${choosenObject.lrEntity.optimizedName}</h5>
              </div>
              <!-- <hr class="object-properties" />-->
              <h6 class="object-properties">EFP <spring:message code="efp.client.val_3.assignments" />:</h6>
              <c:set var="tmp_efp" value="${null}" />
              <c:forEach var="assignment" items="${entityTree.childAssignments[choosenObject.lrEntity.id]}">
                <c:if test="${tmp_efp == null || (tmp_efp != null && !(tmp_efp eq assignment.efp.id))}">
                  <c:if test="${tmp_efp != null}">
                    <hr />
                  </c:if>
                <a href="${pageContext.request.contextPath}/client/efp/efp3?efp_id=${assignment.efp.id}" title="<spring:message code='efp.client.lr.show_efp' />" class="object-properties-efp" style="padding-left: 5px;">${assignment.efp.name}</a>
                </c:if>
                <br />&nbsp;&nbsp;&nbsp;&nbsp;<img src="${pageContext.request.contextPath}/client/resources/graphics/tree-line.gif" height="16" width="16" alt="tree-line" title="" class="tree-icon" /><a href="${pageContext.request.contextPath}/client/value/val3?value_id=${assignment.valueName.id}" title="<spring:message code='efp.client.lr.value' />" class="object-properties-efp">${assignment.valueName.name}</a>
                <c:set var="tmp_efp" value="${assignment.efp.id}" />
              </c:forEach>

efpRegistryServer/src/main/webapp/WEB-INF/jsp/new_efp_result.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<% request.setCharacterEncoding("utf-8"); %>
<% response.setCharacterEncoding("utf-8"); %>
                          <td>
                            <a href="${efp.id}" class="drag_efp ui-draggable" onclick="return false;" style="border: 1px solid black; margin: 1px;">${efp.name}</a>
                          </td>

efpRegistryServer/src/main/webapp/WEB-INF/jsp/new_lr_success.jsp
<?xml version="1.0" encoding="UTF-8" ?>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<% request.setCharacterEncoding("utf-8"); %>
<% response.setCharacterEncoding("utf-8"); %>
<spring:message code="efp.client.gr2.newLr_success" /> lr_id=${lr_object.id}

efpRegistryServer/src/main/webapp/WEB-INF/jsp/wizard.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
  <h3 class="wizard"><spring:message code="efp.client.wizard.wizard" /></h3>
  <p class="wizard">
    <spring:message code="efp.client.wizard.help" />
  </p>
  <a href="${pageContext.request.contextPath}/client/gr/wizardGr" class="menuButtonGrey" style="width: 200px;">
    <spring:message code="efp.client.wizard.startGR" />
  </a>